name             'huevos'
maintainer       'The Authors'
maintainer_email 'you@example.com'
license          'all_rights'
description      'Installs/Configures huevos'
long_description 'Installs/Configures huevos'
version          '0.1.0'
depends          'docker'
